name: spark-thrift

services:

  spark-thrift:
    image: bitnami/spark:3.3
    container_name: spark_thrift
    networks:
      - lakehouse_net

    ports:
      - "10000:10000"
      - "4041:4040"

    volumes:
      - D:/Github/myspark/spark/lakehouse:/data

    command: >
      bash -c "
      /opt/bitnami/spark/sbin/start-thriftserver.sh
        --master spark://spark_master:7077
        --conf spark.sql.warehouse.dir=/data/warehouse
        --conf spark.sql.catalogImplementation=hive
      && tail -f /dev/null"

networks:
  lakehouse_net:
    external: true
