version: "3.9"

services:
  notebook:
    image: jupyter/pyspark-notebook:python-3.10
    container_name: spark-notebook_docker
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ../spark/lakehouse:/data
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    networks:
      - lakehouse_net

networks:
  lakehouse_net:
    external: true
